### ISSUE TITLE
Code is some times missing

### ISSUE THREAD

**Issue by jack1357** [chrisj42/minicraft-plus-revived#107]
When I tried fishing with a wooden fishing rod the game said a class was called that was not defined. Below I have attached an image of the error message:

![An error has occurred 10_11_2019 4_53_22 PM](https://user-images.githubusercontent.com/56456093/66686017-1675cf80-ec4c-11e9-889f-453da700dd94.png)

The first time I started the game, I when into a cave. I could not figure out how to get out because the stair just did not show up.

**Comment by Makkkkus** [comment]
It has something to do with rendering. Could be a memory fault or something

**Comment by africalinguist** [comment]
yeah, this is probably something to do with your computer or your copy of the game (did you try redownloading it?)

**Comment by jack1357** [comment]
When I am playing and perform an action, it sometimes crashes the game and says the action was unable to be preformed. If I reload it there is a different issue to be found.

**Comment by Makkkkus** [comment]
Issue is old, will not fix. Please close.
