### ISSUE TITLE
keys

### ISSUE THREAD

**Issue by vladcsh68** [chrisj42/minicraft-plus-revived#115]
![2020-01-07 at 14-12-56](https://user-images.githubusercontent.com/55958485/71891894-a5658b80-3158-11ea-8550-7ac16b0795f7.png)
I don't know how it happened I just can't play

**Comment by PoKu4** [comment]
you can fix it with try to erase a game file where keys binding are saved in a folder called **playminicraft** and inside of that folder it should have a file called **Preferences.miniplussave**, this file is what you have to erase

### If you're on Windows
The path where **playminicraft** folder is saved it's at `C:\Users\<your username>\AppData\Roaming\playminicraft`, though you can also type `%AppData%\playminicraft` with pressing **Win + R**

### if you're on Linux/Mac
The path where **playminicraft** folder is saved it's at `~/.playminicraft`, also the folder name contains a `.` unlike that Windows

**Comment by africalinguist** [comment]
closing
