### ISSUE TITLE
A ERROR on Eclipse

### ISSUE THREAD

**Issue by anye-dark** [chrisj42/minicraft-plus-revived#121]
The declared package "minicraft.core" does not match the expected package "core"

**Comment by africalinguist** [comment]
what did you mark as the source directory?

**Comment by WothRiss** [comment]
src\

**Comment by Makkkkus** [comment]
Has this been resolved, if so, please close this issue.

**Comment by WothRiss** [comment]
Sorry, I haven't solved it yet...

**Comment by Makkkkus** [comment]
Join the Discord. It is easier to help then. https://discord.gg/ngTJPxX

**Comment by Makkkkus** [comment]
Inactive. Should be closed
