### ISSUE TITLE
Stamina should not be used up if not doing any significant action

### ISSUE THREAD

**Issue by Makkkkus** [chrisj42/minicraft-plus-revived#124]
Right now, if you hit the air you will lose stamina. This is a little bit backwards. Stamina should only be lost when doing an action.

**Comment by Rubiktor012** [comment]
That is how the OG Minicraft works, and hitting is like doing an action (like missing a shot).

**Comment by africalinguist** [comment]
Just gonna close this. I think it's fine since you get stamina back quickly.
