### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by pgattic** [chrisj42/minicraft-plus-revived#125]
In the storyline guide, on the first line of page nine, it says "how may there are", but I would think it should say "how **many** there are".
![image](https://user-images.githubusercontent.com/47119324/77836859-4cdad480-7130-11ea-8bc1-59f85ab5556e.png)

**Comment by Makkkkus** [comment]
Fixed

**Comment by Makkkkus** [comment]
This issue is fixed. Are you able to close it?

**Comment by africalinguist** [comment]
yeah
