### ISSUE TITLE
NPC Villages

### ISSUE THREAD

**Issue by Rubiktor012** [chrisj42/minicraft-plus-revived#126]
So I've been encountering these abandoned villages. I think it would be a good idea to add NPC villages alongside villagers, with a trading system (maybe with gems). If you made that I would be so glad!

Your Minicraft + player:

 - Rubiktor012

**Comment by Makkkkus** [comment]
Good idea, and it has been asked before. This is definitely a TODO, but with low priority.

**Comment by Rubiktor012** [comment]
Great! I'll like to see this in-game. Also, sorry for the slow reply, I do not use GitHub often.

**Comment by Makkkkus** [comment]
Aircraft has added villagers! If you want to try that out; this is the project link: [https://github.com/TheBigEye/Aircraft-Mod/releases](https://github.com/TheBigEye/Aircraft-Mod/releases).

**Comment by africalinguist** [comment]
Personally I don't think it would fit with the theme of the game, since notch created the game with the prompt "alone"

**Comment by chrisj42** [comment]
Old suggestion, removing. Feel free to suggest this in other places like the discord.
