### ISSUE TITLE
What you think about nea graphics?

### ISSUE THREAD

**Issue by duhich167** [chrisj42/minicraft-plus-revived#128]
I can create graphics for minicraft for free. What do you think about this?

**Comment by Makkkkus** [comment]
Join the discord: https://discord.me/minicraft

**Comment by duhich167** [comment]
Okey. What i need to do now?

**Comment by Makkkkus** [comment]
Talk there

**Comment by Makkkkus** [comment]
Over a month old; should probably be closed.
