### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by Rubiktor012** [chrisj42/minicraft-plus-revived#129]
There are these books, with stories in them. Why not be able to write stories ourselves? Maybe even change the book color (Or the possibility of encountering other player's books on our world, even when on singleplayer mode!).

**Comment by Makkkkus** [comment]
Yes

**Comment by africalinguist** [comment]
Answer for now is no. I tried to write the server code to get this to work, but it was too difficult for me at the time. If anyone wants to try and write that code, they can.

**Comment by chrisj42** [comment]
once again old suggestion that I'm sure we have on record elsewhere.
