### ISSUE TITLE
isnt really an issue but how open

### ISSUE THREAD

**Issue by ilovetabs** [chrisj42/minicraft-plus-revived#131]
i got the  code and the other files but how open??
is there an exe? do i need to buy it?

**Comment by duhich167** [comment]
You need to download jar file

**Comment by duhich167** [comment]
https://github.com/chrisj42/minicraft-plus-revived/releases

**Comment by ilovetabs** [comment]
i did

**Comment by ilovetabs** [comment]
wait was i supposed to only download that then

**Comment by ilovetabs** [comment]
i did download the .jar wat now
_i dont get it_

**Comment by ilovetabs** [comment]
- [ 1 ]  download the jar file done

**Comment by Makkkkus** [comment]
open the jar file.

**Comment by Makkkkus** [comment]
If you do not have Java installed you have to install java at https://java.com

**Comment by ilovetabs** [comment]
i have normal minecraft does that mean i have java?

**Comment by ilovetabs** [comment]
i dont see any thing i can run also im using winrar

**Comment by Makkkkus** [comment]
Yes, you need java. Minicraft Plus and Minecraft are not related.

**Comment by ilovetabs** [comment]
ohhh

**Comment by ilovetabs** [comment]
then what?

**Comment by Makkkkus** [comment]
Run the game

**Comment by ilovetabs** [comment]
where? i dont see an exe or any file to run

**Comment by ilovetabs** [comment]
> Run the game

where? i dont see an exe and i downloaded java

**Comment by ilovetabs** [comment]
`print "hello world"`

**Comment by duhich167** [comment]
Just run the jar file.

**Comment by IdotMaster1** [comment]
You are a idiot

**Comment by IdotMaster1** [comment]
You run the  jar file
Double click it

**Comment by ilovetabs** [comment]
o k

**Comment by ilovetabs** [comment]
it wont work it just brings up win rar

**Comment by Makkkkus** [comment]
Right click > Open With > Java

**Comment by ilovetabs** [comment]
i dont see that

**Comment by ilovetabs** [comment]
it just says open and thats it

**Comment by ilovetabs** [comment]
oh

**Comment by ilovetabs** [comment]
there ut i

**Comment by 2sday** [comment]
can someone tell me what jar file to open pls

**Comment by duhich167** [comment]
https://github.com/chrisj42/minicraft-plus-revived/releases

**Comment by duhich167** [comment]
This is minicraft_2_0_6_official.jar
