### ISSUE TITLE
how do open it

### ISSUE THREAD

**Issue by 2sday** [chrisj42/minicraft-plus-revived#132]
is it because i took the files out of the zip file by coping then and pasted them onto my computer? idk

**Comment by VojtechBrezina** [comment]
I reccomend, you read #131 first.

**Comment by 2sday** [comment]
ok i did and still dont know how to open it

**Comment by 2sday** [comment]
because i dont know what jar file to open

**Comment by 2sday** [comment]
srsly pls help how am i supposed to open it

**Comment by duhich167** [comment]
https://github.com/chrisj42/minicraft-plus-revived/issues/131#issuecomment-632561422

**Comment by 2sday** [comment]
i am literally confused someone help and #131 doesn't help i need actual help with this

**Comment by VojtechBrezina** [comment]
- On the releases page, download `minicraft_plus_2.0.6_official.jar`
- Doubleclick the file.

- If that does not work, download Java (a quick google search should all you need) and try again.

**Comment by Makkkkus** [comment]
Nearly a month since last comment. Should be closed.
