### ISSUE TITLE
Picked up dungeon chests are broken in many ways

### ISSUE THREAD

**Issue by TheRamenChef** [chrisj42/minicraft-plus-revived#139]
Once unlocked, dungeon chests can be picked up and stowed in your inventory. But in the inventory, they do not have a proper sprite, just an unused point in the spritesheet.

**Comment by africalinguist** [comment]
While looking into this I have discovered a large number of bugs having to do with picked up dungeon chests, including placed dungeon chests not being saved. So.

**Comment by africalinguist** [comment]
Finally got back to working on minicraft+, this is almost entirely fixed with new commits.
