### ISSUE TITLE
Animals dissapear

### ISSUE THREAD

**Issue by Makkkkus** [chrisj42/minicraft-plus-revived#148]
Animals disappear after a while regardless if it is in view or not. Functionality should be added to keep animals, and de-spawning should be prevented while in view.

**Comment by lino-levan** [comment]
I feel like name tags as a concept need to be talked about a lot more in depth before this issue can really be resolved.

**Comment by lino-levan** [comment]
At this point, I have written most of the code for name tags to be functional as well as fixing animals respawning while players are looking at them.  I just want to polish some things before doing a PR. Should I do one PR for the animal respawning in view and one PR for the name tag or should I just combine both of them?

**Comment by Makkkkus** [comment]
I won't accept the name tags yet. It doesn't fit with the game.
