### ISSUE TITLE
plz add music from Minicraft Flash :D

### ISSUE THREAD

**Issue by I-am-the-Users** [chrisj42/minicraft-plus-revived#158]
_these music are not mine!_
**Source: Minicraft Flash**

[Game Manu Music](https://drive.google.com/file/d/1m9V1KzGV6stXoSUJtdcYG44e6btafk5q/view?usp=sharing)

[Game background music](https://drive.google.com/file/d/1XDJYPw54-UKCTo9g-zMp_77CqQKbSSUv/view?usp=sharing)

**Comment by I-am-the-Users** [comment]
> _these music are not mine!_
> **Source: Minicraft Flash**
> 
> Game background music:

**Comment by Makkkkus** [comment]
This will probably not be implemented in this version of the game, but you can ask some of the developers for other versions on our [Discord](https://discord.me/minicraft).
