### ISSUE TITLE
Blue color pallete?

### ISSUE THREAD

**Issue by kena006** [chrisj42/minicraft-plus-revived#159]
for some reason everything is tinted blue and it looks awful
![Screenshot 2021-04-07 3 24 10 PM](https://user-images.githubusercontent.com/82118161/113922505-5a03b800-97b5-11eb-8855-eef324ae2e8e.png)

**Comment by alice39** [comment]
What version are you using? Also before to look like tinted blue, do you remember to change some settings of game?

**Comment by Makkkkus** [comment]
I have seen just the same error with another project

**Comment by TheBigEye** [comment]
I've seen the same thing in some games recently, most likely the graphics card driver that turns hot color tones like red to cold tones like blue

**Comment by kena006** [comment]
I made this comment a while ago, but as far as I remember, I either
reinstalled linux, or I did something else, but i did get it to display the
correct colors.

**Comment by Litorom** [comment]
Should this be marked closed then? Since it isn’t an issue with the game but rather java.
