### ISSUE TITLE
Fullscreen mode?

### ISSUE THREAD

**Issue by ii-Python** [chrisj42/minicraft-plus-revived#160]
Is there any sort of way to start Minicraft in a fullscreen state?
If there isn't, it could probably be an option or a command-line argument (--fullscreen, -f, etc.).

If there is one, can somebody please tell me what it is?
I would love to create a MinicraftOS, although that's not very possible without having **some** form of a fullscreen option.

**Comment by chrisj42** [comment]
related pull request has been merged.
