### ISSUE TITLE
Minicraft Java Error

### ISSUE THREAD

**Issue by bokoblingaming20** [chrisj42/minicraft-plus-revived#164]
When I open Minicraft+ it says " java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at minicraft.saveload.Load.loadPrefs(Load.java:284)
	at minicraft.saveload.Load.<init>(Load.java:114)
	at minicraft.core.Game.main(Game.java:127). Is there anything you can do to fix this problem?

**Comment by TheBigEye** [comment]
Did you try to delete the game settings?
If you are in windows go to the Appdata folder (press the **Win** + **R** keys and tee a box will appear, there you write **%appdata%**, it will take you to a folder, in that folder you look for the **Playminicraft** folder, then **mods**, then **Minicraft plus**, and delete the 2 files that will appear)

**Comment by bokoblingaming20** [comment]
> Did you try to delete the game settings?
> If you are in windows go to the Appdata folder (press the **Win** + **R** keys and tee a box will appear, there you write **%appdata%**, it will take you to a folder, in that folder you look for the **Playminicraft** folder, then **mods**, then **Minicraft plus**, and delete the 2 files that will appear) 😊
> 
> You can also try deleting the **Playminicraft folder** if it still doesn't work (notice, deleting the entire folder will delete your worlds)

**Comment by bokoblingaming20** [comment]
Thanks. It worked.
