### ISSUE TITLE
Dungeon chests generation

### ISSUE THREAD

**Issue by pelletsstarPL** [chrisj42/minicraft-plus-revived#183]
![obraz](https://user-images.githubusercontent.com/54317957/131178635-e09b9118-474a-4333-b69f-4011964d03d2.png)

Make dungeon chest generate more on-sight. Sometimes they generate very very deep in dungeon walls bringing a lot of confusion.

**Comment by lino-levan** [comment]
@pelletsstarPL do you have the seed for the world in the screenshot?

**Comment by TheBigEye** [comment]
In short this would have to be changed in level.java, should only generated on obsidian bricks. 
![image](https://user-images.githubusercontent.com/63316583/147482856-edfc4a9c-ac56-43d3-b373-80aafa070d71.png)
