### ISSUE TITLE
FPS doesn't match settings

### ISSUE THREAD

**Issue by Makkkkus** [chrisj42/minicraft-plus-revived#200]
When I set my FPS to 60 in the settings the actual FPS is closer to 47.

**Comment by Litorom** [comment]
Issue #200!! We have 200!!!

**Comment by lino-levan** [comment]
> When I set my FPS to 60 in the settings the actual FPS is closer to 47.

How did you test this? Is there an in-game counter for FPS hidden somewhere?

**Comment by Makkkkus** [comment]
> How did you test this? Is there an in-game counter for FPS hidden somewhere?

F3

**Comment by lino-levan** [comment]
Don't know why I didn't think of that
