### ISSUE TITLE
Game crashes when pressing ESC after deleting world

### ISSUE THREAD

**Issue by SashaTalk** [chrisj42/minicraft-plus-revived#211]
Game crashes when jumping to previous menu after world deleting

**Steps to reproduce the behavior:**
1. Start game
2. Select "Singleplayer"
3. Press "D"
4. Press "Enter" to delete highlighted world
5. Press "Enter" again to confirm deleting
6. Press "ESC"
7. Press "Enter"

**Expected behavior**
Game crashed after pressing "Enter"

**Video**
https://user-images.githubusercontent.com/76222964/139535643-43937bff-3640-4f4a-8c2f-f6c7e89a7093.mp4

**Desktop:**
 - OS: Microsoft Windows 10 21H1 (10.0.19043.1288)
 - Version 2.0.7

**Comment by Makkkkus** [comment]
I cannot replicate the problem.

**Comment by lino-levan** [comment]
I was able to replicate the error. May look into fixing this is a little bit.

https://user-images.githubusercontent.com/11367844/143929670-099571a3-08c4-446f-bd8b-0aa6196faec9.mp4

**Comment by Makkkkus** [comment]
Aha

**Comment by Litorom** [comment]
This code appears to be what the error shows, line 77.

for (File file : list) {
	file.delete();
}
world.delete();

**Comment by lino-levan** [comment]
Can confirm. Replacing it with:

```java
if(list != null) {
  for (File file : list) {
	  file.delete();
  }
}
```

Fixes the crash but the real question is why does pressing "esc" return to the delete world menu?

**Comment by Litorom** [comment]
This is where the “ESC” key usage is used.
https://github.com/chrisj42/minicraft-plus-revived/blob/master/src/main/java/minicraft/screen/Display.java
Brings you back to the previous menu. This must be changed so you can’t do that in this menu.

**Comment by lino-levan** [comment]
@Makkkkus Should this issue be closed?
