### ISSUE TITLE
[FEATURE] Adding raw obsidian for logic reasons and corresponding Decor Tiles

### ISSUE THREAD

**Issue by Litorom** [chrisj42/minicraft-plus-revived#219]
**Additional Info (12/07/2021):**
Add DecorTiles for more tile diversity. 

**Is your feature request related to a problem? Please describe.**
The way water and lava make obsidian “planks” makes no sense and is illogical.

**Describe the solution you'd like**
I recommend changing the texture and name to something like “Raw Obsidian” can be a new tile which in this case can be mined and used to make Obsidian Planks.

**Describe alternatives you've considered**
An alternative that requires less coding is renaming it to obsidian and changing the texture.

**Comment by Litorom** [comment]
Assigning myself to Issue

Already Completed:
Raw Obsidian Item, Tile, Textures

Included but not directed explained in issue:
Added Raw Stone Tile, Texture
In progress Ornate Stone (Decor)
In progress Obsidian Tiles (Decor)

**Comment by Litorom** [comment]
Completed:
Raw Obsidian Item, Tile, Textures
Added Raw Stone Tile, Texture
Added Ornate Stone (Decor)
Added Obsidian Tiles (Decor)
In progress Bug Fixing.

**Comment by lino-levan** [comment]
I feel like this should be un-closed

**Comment by Litorom** [comment]
Can’t be unclosed since the PR assigned to it was merged.

**Comment by Litorom** [comment]
@Makkkkus reassign me please. Also I recommend changing Obsidian to raw Obsidian since Obsidian bricks uses that ID

**Comment by TheBigEye** [comment]
It would be nice to make a kind of converter ... when loading an ancient world the game would search all obsidian brick tile entries within the save files and change them to the current ID

**Comment by Makkkkus** [comment]
That is what Load.java is for

**Comment by lino-levan** [comment]
Ideally we would have a loader for each version that takes the previous version file and upgrades it to the next version. This would allow for so much more flexibility in the saving/loading system and means it would be significantly easier to move to a json format for world saves if we ever decide to do that.

I'm going to open an issue for this, though it is probably unrealistic to expect it to get done by 2.1.0

**Comment by Litorom** [comment]
> It would be nice to make a kind of converter ... when loading an old world (2.0.7) the game would search all obsidian brick tile entries within the save files and change them to the current ID

New tiles don’t affect old tiles.
