### ISSUE TITLE
Improve stairs display

### ISSUE THREAD

**Issue by pelletsstarPL** [chrisj42/minicraft-plus-revived#228]
**How about making stairs on cloud floor look better?**
Atm those look like:
![obraz](https://user-images.githubusercontent.com/54317957/144758532-71b64204-00b1-4a59-aae0-f1e51007797b.png)

Wouldn't it be better to make their display look like: 
![obraz](https://user-images.githubusercontent.com/54317957/144758538-47b07828-8806-4158-80ac-08c3e8d2ff7d.png)
this?

**Comment by lino-levan** [comment]
Someone should probably rewrite the stairs tile at some point
