### ISSUE TITLE
[FEATURE] Be able to select, copy or paste text within the game

### ISSUE THREAD

**Issue by TheBigEye** [chrisj42/minicraft-plus-revived#234]
**Describe the solution you'd like**
Could use the classic keyboard combinations, such as **CTRL + A** to select all the text within a text box (it would be simple to do so, the selection should invert the colors of the letters and the background of the selected text), **CTRL + C** to copy the selected text to the clipboard and **CTRL + V** to paste the text.

**Comment by Litorom** [comment]
I would like to be assigned to this.

**Comment by Litorom** [comment]
![copypastecut](https://user-images.githubusercontent.com/70768734/147389425-21907232-b5a4-4647-bae1-4eaca8b4099a.gif)

Almost finished

**Comment by Makkkkus** [comment]
Good

**Comment by Litorom** [comment]
Should be closed, fixed by #247
