### ISSUE TITLE
Redesign loading system to make one loading file per version to update files

### ISSUE THREAD

**Issue by lino-levan** [chrisj42/minicraft-plus-revived#235]
Essentially, this change would allow for significantly more flexibility in changing the loading system for each version.

### The idea is:
- Each version has a file to update from the previous version to the next version
- We can upgrade any file from a previous version to any future version by iterating through each save file, upgrading the save file at each step

This allows for a lot more flexibility in saving/loading and allows for the saving/loading files to finally be readable (and writeable).

### Example:
File: ReallyOutdatedSave.miniplussave

Steps:
1. ReallyOutdatedSave.miniplussave gets run through LegacyLoad to produce OutdatedSave.miniplussave
2. OutdatedSave.miniplussave gets run through the current Load.java to produce a 2-0-7-Save.miniplussave
3.  2-0-7-Save.miniplussave gets run through the (proposed) 2-1-0-Load.java to upgrade the save file to 2-1-0-Save.miniplussave
4. (In the future) 2-1-0-Save.miniplussave is ran through 2-X-X-Loading.java to upgrade the save file to 2-X-X-Save.json

Note: The file names are just to help understanding, we should not change the names of the files when loading/saving unless we care about backups or something

**Comment by Makkkkus** [comment]
no

**Comment by lino-levan** [comment]
Spaghetti code it is
