### ISSUE TITLE
Crash on linux

### ISSUE THREAD

**Issue by africalinguist** [chrisj42/minicraft-plus-revived#24]
OS: Ubuntu 16.04

Game Version: 2.0.4-official

When I go to the play menu and try to type in the name, the game freezes after I type one or two characters.

**Comment by africalinguist** [comment]
also, after two button presses on any menu (i.e. scrolling down at main menu) the game stops responding.

**Comment by chrisj42** [comment]
that's strange. Could you try running it from a command line and seeing if anything prints out?

**Comment by macsmac** [comment]
+1. Does not print out any errors
Ubuntu 16.04, kernel 4.13

![photo_2018-06-19_15-19-44](https://user-images.githubusercontent.com/18601048/41591946-986862a6-73d4-11e8-8052-280d53960b84.jpg)

**Comment by africalinguist** [comment]
this shows:
afyber@afi-Lenovo:~/minicraft-plus$ java -jar minicraft_plus_2.0.4_official.jar --debug
determined gameDir: /home/afyber/.playminicraft/mods/Minicraft_Plus
initializing tile list...
resetting ..
fetching release list from github...
latest version = 2.0.4
window closing

**Comment by chrisj42** [comment]
oh interesting, so that means that something tries to close the window...

**Comment by africalinguist** [comment]
this occurs with all versions after 2.0.3-official, including dev versions, I was not able to test 2.0.4 dev1 accurately because of an error:

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/media/AudioClip
	at minicraft.Sound.<init>(Sound.java:21)
	at minicraft.Sound.<clinit>(Sound.java:7)
	at minicraft.screen.Menu.tick(Menu.java:147)
	at minicraft.screen.Display.tick(Display.java:82)
	at minicraft.screen.TitleMenu.tick(TitleMenu.java:107)
	at minicraft.Game.tick(Game.java:488)
	at minicraft.Game.run(Game.java:1156)
	at minicraft.Game.main(Game.java:1335)
Caused by: java.lang.ClassNotFoundException: javafx.scene.media.AudioClip
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by chrisj42** [comment]
The game is on 2.0.4 official now, so any problems with versions below that I can't really do anything about...

**Comment by africalinguist** [comment]
that shows that the change is in between 2.0.3-official and 2.0.4-dev2, so you can look in the diff for those two

**Comment by hippo-o-matic** [comment]
I have the same problem, after the second keypress it freezes.
OS: Ubuntu 16.04

![vokoscreen-2018-09-24_20-37-10](https://user-images.githubusercontent.com/24530869/45991535-32570500-c03a-11e8-9f4f-3a0fbe3f2179.gif)

It doesn't actually close the window itself, just freezes.

**Comment by chrisj42** [comment]
hmm, does it happen if you select "play" instead of "join online world"?

**Comment by chrisj42** [comment]
heh, great! you're welcome.

**Comment by africalinguist** [comment]
I found the root of the problem. I was using Java 8, but with Java 10 it works.

**Comment by chrisj42** [comment]
if you are using openJDK, try installing the jdk/jre 8 from this ppa, it's what I use (it's the official version): http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
