### ISSUE TITLE
Remove green dots from dirt dungeon tile texture

### ISSUE THREAD

**Issue by pelletsstarPL** [chrisj42/minicraft-plus-revived#241]
![obraz](https://user-images.githubusercontent.com/54317957/145837731-36e4c524-e059-40fc-be8d-b4257d78c399.png)
Those green dots make it look weird tbh
On screenshot you have how you can improve it.

**Comment by TheBigEye** [comment]
🤔

**Comment by TheBigEye** [comment]
I think this should be closed
