### ISSUE TITLE
[FEATURE] Some old features could be re-added

### ISSUE THREAD

**Issue by TheBigEye** [chrisj42/minicraft-plus-revived#244]
## It would be nice to re-add some features from old versions:

- #### When swimming, the sprite of waves in the water is supposed to be animated
![test](https://user-images.githubusercontent.com/63316583/147415007-d5f116e2-0991-475d-add3-4921da0f6f15.gif)

- #### Creepers should blink before exploding.
![test](https://user-images.githubusercontent.com/63316583/147415046-c0736ee6-1c41-4713-ae6b-29df4e6b890a.gif)

- #### The air wizard, being low on life, should blink.
![test](https://user-images.githubusercontent.com/63316583/147415714-a6c26d3f-b23b-4239-a6de-8e3329e8ae9d.gif)
You could create a method that overwrites the sprite colors so as not to have to use a grayscale one

- #### Items, damage particles and sparks should have shadows.
![test](https://user-images.githubusercontent.com/63316583/147414964-2d534822-00e6-4386-8468-224fae73a096.gif)

- #### The pow glove should appear for a few seconds when trying to take some furniture as it happened before (I don't understand why it was eliminated)
![test](https://user-images.githubusercontent.com/63316583/147415214-c2ff3b08-2957-4a49-b1ee-dc3a0fbb05fb.gif)

- #### Spawner items should have the colors of the associated mob.
![test](https://user-images.githubusercontent.com/63316583/147415440-95fed6cc-aed6-4ac2-a335-7c9a08434028.gif)
(it would be something simple to add), a method is created for example like this:
```
public Spawner(MobAi mob, int color) {
     etc, etc..
}
```
If the color is specified, the item will use a grayscale sprite, if not, it will use the normal blue sprite

**Remember that Minciraft plus is based on the original Minicraft, little details like these make the difference**

**Comment by Litorom** [comment]
I cannot find when it was removed. @chrisj42 if possible may I have the dates so I can find the code and re-add to Minicraft. Of course I’ll have to change it’s coding.

**Comment by chrisj42** [comment]
This is odd, most of these weren't broken when I last worked on it, so try looking back at some of my releases. The water sprites specifically I remember messing with. The spawner I can understand because the spritesheet became colored.
As for the rest I don't know either. If you wish to find the times they worked, you can download different versions (be sure to backup data first), but I would recommend going into the code and figuring it out, provided you have a basic understanding of the codebase as a whole.

**Comment by Litorom** [comment]
For these to exist again the whole Sprite would have to be rewritten. I can’t find a way to add colors to the Spawners, or make Creepers and Air Wizards blink without the need for gray scale sprites or the addition of new Sprites.

**Comment by TheBigEye** [comment]
well, you don't need to rewrite anything (that would complicate it more), only those that are possible to do at this time would be added, that's why I wrote "Some" in the title

**Comment by Makkkkus** [comment]
Adding more textures for different spawners is definitely worth it

**Comment by TheBigEye** [comment]
> Adding more textures for different spawners is definitely worth it

ok, that works :)

**Comment by Makkkkus** [comment]
Most have been fixed
Eye can reopen if he wants

**Comment by TheBigEye** [comment]
Ok, I will reopen it when by chance I manage to add something else, or if someone does
