### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by AstroCat22** [chrisj42/minicraft-plus-revived#255]
**Describe the bug**
Cannot select a Texture pack

**To Reproduce**
In the "texture packs" window, the pack shows up, but I can't select it.

**Expected behavior**
I expected the texture pack to be selected and visible in-game

**Platform:**
 - OS: MacOS Catalina
 - Version 10.15.7

**Comment by Litorom** [comment]
Might be a key issue for Mac as key definitions were based Windows Users.

**Comment by lino-levan** [comment]
As someone who is on a Mac, I have not experienced any issues(?) @AstroCat22 could you send a link to the texture pack you are using?

**Comment by AstroCat22** [comment]
SOLVED pack was formatted incorrectly.
