### ISSUE TITLE
How can I add my localization?

### ISSUE THREAD

**Issue by TerisbackDev** [chrisj42/minicraft-plus-revived#26]
I recently met this game, and I want to make a translation into my own language.
But how to do that?

**Comment by Kerellll** [comment]
Are you from Nerkin? :D
I would also like something to add Russian.

**Comment by TerisbackDev** [comment]
Yes, I am from Nerkin.
I'm very impressed with the game, so I decided to do the localization.
By the way, I already made a pull request

**Comment by TerisbackDev** [comment]
#27

**Comment by chrisj42** [comment]
Well if you want to add it now, there are a few files in https://github.com/chrisj42/minicraft-plus-revived/tree/master/src/resources/localization that you can copy. Just follow their lead.

It isn't perfect, though, there are a few different strings which aren't included. We were thinking of remaking the localization a little bit, though I don't know if that's really going to happen. If it does, though, then you may have to redo the localization... reformat it, at least.

**Comment by chrisj42** [comment]
Oh right, there's a bit of an issue with the font... the font is part of the spritesheet, and so it only supports the characters that are in there...
https://github.com/chrisj42/minicraft-plus-revived/blob/master/src/resources/icons.png

**Comment by chrisj42** [comment]
if you want other characters, then you're gonna have to add them to the spritesheet yourself.

**Comment by TerisbackDev** [comment]
I drew
#27
