### ISSUE TITLE
Game Crashes when loading outdated Preferences.JSON

### ISSUE THREAD

**Issue by lino-levan** [chrisj42/minicraft-plus-revived#260]
**Describe the bug**
Game crashes when opening due to outdated Preferences.json (specifically due to trying to load difficulty if it doesn't exist)

**To Reproduce**
1. Open the game with any old Preferences.json file (an example is provided below)
```json
{"autosave":"true","savedUUID":"","savedUsername":"","keymap":["MOVE-UP;UP|W","MOVE-DOWN;DOWN|S","MOVE-LEFT;LEFT|A","MOVE-RIGHT;RIGHT|D","CURSOR-UP;UP","CURSOR-DOWN;DOWN","CURSOR-LEFT;LEFT","CURSOR-RIGHT;RIGHT","SELECT;ENTER","EXIT;ESCAPE","QUICKSAVE;R","ATTACK;C|SPACE|ENTER","MENU;X|E","CRAFT;Z|SHIFT-E","PICKUP;V|P","DROP-ONE;Q","DROP-STACK;SHIFT-Q","SEARCHER-BAR;F","PAGE-UP;PAGE_UP","PAGE-DOWN;PAGE_DOWN","PAUSE;ESCAPE","POTIONEFFECTS;P","INFO;SHIFT-I","FULLSCREEN;F11"],"sound":"false","fps":"30","lang":"english","version":"2.1.0-dev2","skinIdx":"3","savedIP":""}
```
2. See error

**Expected behavior**
The game should not crash, instead it should actually play (Add the difficulty setting if not exist).

**Screenshots**
<img width="576" alt="Screen Shot 2022-01-19 at 7 58 04 AM" src="https://user-images.githubusercontent.com/11367844/150167683-35cb3f40-969c-457c-830c-0792816d96de.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 11
 - Version 2.1.0dev2

**Comment by Litorom** [comment]
I also encountered this issue, had to manually update the json file.
