### ISSUE TITLE
how to bring back the buttons appointment 

### ISSUE THREAD

**Issue by CodeDog112** [chrisj42/minicraft-plus-revived#28]
I accidentally made a mistake in the purpose of the buttons and now can not return

**Comment by PumpkinVideos** [comment]
Im too do that mistake.How did we return it?

**Comment by TerisbackDev** [comment]
You can delete Preferences file from AppData/Roaming/playminicraft/mods/minicraft_plus/

**Comment by PumpkinVideos** [comment]
Yes, this working
