### ISSUE TITLE
Doesn't load up.

### ISSUE THREAD

**Issue by ShaiZoYT** [chrisj42/minicraft-plus-revived#33]
I am a windows user. I downloaded Minicraft Plus, the lastest version. It is a very simple and funny game that I liked. When I ended up playing, I saved the world and quit the game. Now the game doesn't even start. Only the logo appears on the middle of the screen. Then disappiers instantly and the game DOESN'T load up. Can you help me please?

**Comment by chrisj42** [comment]
try copying your world to your desktop or something, and then deleting all your local files. That often works.
If it does work, then copy just your world save (the folder inside "saves") to the actual "saves" folder the game uses. Tell me if it loads then, or if deleting your local files didn't work to begin with.
