### ISSUE TITLE
Says Multiplayer, but doesn't do anything

### ISSUE THREAD

**Issue by hwd2002** [chrisj42/minicraft-plus-revived#34]
The Minicraft Plus 2.0.4 says it has multiplayer, but I can not find any tutorials on it. If you know how, maybe you could enlighten me. There seems to be a few servers out there(Listed on Dischord), but I can't connect. The error is:

Could not connect to server:
Could not connect to playminicraft account server, but no login data saved; cannot enter offline mode.

So I am probably totally screwing it up here, but if anyone knows how, could they point me in  the right direction? Do I need to enter account details somewhere?
 Thanks!

**Comment by hwd2002** [comment]
Turns out you need to sign in using 2.0.4 Development version and then use the Normal version to connect. This is not the best way to do it, but it works.

**Comment by chrisj42** [comment]
I believe the login issue is something to due with internet? If not then I am not sure why, simply that it had issues connecting with the authentication server. playminicraft.com is where the game goes to get login information, and it is also where you register for an account. Minicraft servers are the ones listed on the discord.

When you're entering the ip of a minicraft server, does it say anything about "offline mode" or "local servers" or something on the page? This would be helpful to know.

It is a bit odd that you can only log in on the older version, is that still the case if you logout and try it now?

**Comment by hwd2002** [comment]
Well, I never got to where you enter ANY information whatsoever, I just hit Join Online World and it spits out the error. But I figured out that the Preferences file from the old version that has the login data also works with the new version. Now I can connect the new version just fine and don't need to enter in anything but the IP, but it just never gave me a chance to login.

**Comment by chrisj42** [comment]
if you want you can logout and try and login again, the ip page tells you what keys to press to logout... I would recommend saving a copy of the preferences file first though. Just in case.

**Comment by hwd2002** [comment]
Soo, Yes. It does let me re-login now, It just took me a few weeks to figure out how to. Unfortunately this method doesn't work on my Raspberry Pi, just Windows. :-(

**Comment by chrisj42** [comment]
darn. Oh well. Maybe if I get a raspberry pi someday I'll try and figure out why it doesn't work.
