### ISSUE TITLE
The island terrain keeps glitching when come back

### ISSUE THREAD

**Issue by animewolf07** [chrisj42/minicraft-plus-revived#36]

**Comment by chrisj42** [comment]
how does it glitch? And has this happened for multiple saves? I may know of the bug you're talking about.

**Comment by animewolf07** [comment]
It would send me to some where in the ocean and nothing really works then, so I have to make a new world. yes this has happend multiple times.

**Comment by africalinguist** [comment]
I find that when coming back to a world, sometimes your character will disappear and you will be unable to move, along with weird terrain stuff.

**Comment by chrisj42** [comment]
Do you notice a sort of veritcally shredded pattern in the terrain with strips of water?

**Comment by chrisj42** [comment]
There it is. If you can consistently reproduce this from a new world, then this might finally get squished. It has to be a new world because the tiles are probably just saved that way now.

**Comment by africalinguist** [comment]
From what I can tell it looks like the player entity is never added, but I have seen sheep in this glitch, so those are spawning correctly.

**Comment by chrisj42** [comment]
the player is something else, first the terrain needs to be fixed.

**Comment by chrisj42** [comment]
w00t fixed
I think
