### ISSUE TITLE
tool durability don't reset

### ISSUE THREAD

**Issue by Dioarya** [chrisj42/minicraft-plus-revived#37]
tool durability don't change when making new tool, the durability still is the same as the last [tool](url) durability

**Comment by Dioarya** [comment]
i meant tool durability don't reset in the new tool

**Comment by chrisj42** [comment]
really now? so after using the first tool up some, crafting a second tool (of the same type or a different type?) makes a tool with the same durability as the first one?
Try to provide a sequence of steps involving the crafting and usage of the tools, starting from not having any tools, that results in the bug you're experiencing. This is the most efficient way to debug something.

**Comment by chrisj42** [comment]
fixed in latest build

**Comment by Dioarya** [comment]
Thanks for the fix!

**Comment by chrisj42** [comment]
you're welcome. :D
