### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by apidya** [chrisj42/minicraft-plus-revived#41]
Has anybody tried porting this to Android yet?

**Comment by chrisj42** [comment]
Pigeoncraft is a really good one

**Comment by lovetocode999** [comment]
Pigeoncraft is not as good as Minicraft+

**Comment by chrisj42** [comment]
Well then, I suppose you could port it then if you really want to. Still no iOS port though... ;)

**Comment by lovetocode999** [comment]
Sounds like fun!
