### ISSUE TITLE
Arrows create glitched entities on server

### ISSUE THREAD

**Issue by africalinguist** [chrisj42/minicraft-plus-revived#44]
when shooting arrows at cows while on a server, sometimes (very occasionally) they will glitch and become all white until you kill them.
![Screenshot from 2019-03-22 19-23-31](https://user-images.githubusercontent.com/26539285/54824195-981a0600-4cd8-11e9-9fa4-eea741f29965.png)

**Comment by chrisj42** [comment]
ah yes, this reminds me of creepers, creepers also have weird rendering glitches.

**Comment by Makkkkus** [comment]
I think this is fixed after the color overhaul

**Comment by africalinguist** [comment]
ok
