### ISSUE TITLE
I can't open it

### ISSUE THREAD

**Issue by B1ackydecatty** [chrisj42/minicraft-plus-revived#46]
I tried to open minicraft plus revived but i can't seen to be open

**Comment by B1ackydecatty** [comment]
I keep getting an error message

**Comment by africalinguist** [comment]
you need to run it with java, and what's the error?

**Comment by B1ackydecatty** [comment]
I right-clicked the file and clicked "Open With" and Click Java but it doesn't seem to open

**Comment by B1ackydecatty** [comment]
even i right-clicked the .jar file tho not other stuff

**Comment by chrisj42** [comment]
Could you provide a screenshot of the error message please?

**Comment by B1ackydecatty** [comment]
i tried but it goes away quickly, i can't take a screenshot unless i record it

**Comment by chrisj42** [comment]
Hmm have you played an older version of the game before? Sometimes it has issues reading old preference data, and deleting that often fixes the issue for people. Doesn't apply if you haven't played the game before though.

**Comment by B1ackydecatty** [comment]
you mean original version of minicraft? no, i didn't play it.

**Comment by B1ackydecatty** [comment]
I straight up just install this version of minicraft

**Comment by chrisj42** [comment]
try going to %APPDATA%/playminicraft/mods/Minicraft_Plus/ and delete all the content there. If you haven't played then you shouldn't have any world data or anything to worry about losing.
