### ISSUE TITLE
Click to focus text bug

### ISSUE THREAD

**Issue by africalinguist** [chrisj42/minicraft-plus-revived#48]
in the "Click to focus" text box the spaces are black instead of blue
![Screenshot from 2019-03-23 16-09-31](https://user-images.githubusercontent.com/26539285/54865849-5487d080-4d9a-11e9-95c1-be159658f745.png)

**Comment by chrisj42** [comment]
So it is!

**Comment by africalinguist** [comment]
fixed by #49
