### ISSUE TITLE
Very simple item duplication on servers

### ISSUE THREAD

**Issue by Tr0d0n** [chrisj42/minicraft-plus-revived#74]
It is possible to get a lot of items in a server by duplicating them.

Instructions:

1. Hold an item that has an animation of usage. Food, armor, and potions, for example, won't work.
2. Use the item
3. Open the inventory quickly.

If you open the inventory quickly enough, you will end up in a short time, usually nearly instantly, with the item both in the inventory list and in the equipped item slot. If it's a placeable item, it won't appear in the equipped item slot and instead will be placed.

Non-tool duplicated items can't be used until the player does one of the following:

- Drops the whole stack on the floor and picks the items
- Puts the item stack in a container and take them out
- Reconnects to the server

**Comment by Makkkkus** [comment]
Still works; I used this to duplicate flowers.

**Comment by Makkkkus** [comment]
![image](https://user-images.githubusercontent.com/37084190/110747298-77894480-823e-11eb-96d4-b5a2a46d11df.png)
