### ISSUE TITLE
Health, hunger and armor bars changing to previous values randomly on servers

### ISSUE THREAD

**Issue by Tr0d0n** [chrisj42/minicraft-plus-revived#76]
Health, hunger and armor bars changing to previous values randomly on multiplayer.
This can both increase the values and decrease it and happens randomly. This can happen multiple times with the same values.
Examples:

- Eating a golden apple, which should replenish the hunger bar completely, and after not very long having the hunger bar go back to its original value.
- Fighting a lot of monsters, and during the fight having some of the hearts regenerate spontaneously.

The only way currently proven to stop this is by reconnecting to the server.

**Comment by Litorom** [comment]
Would changing the “Update” variable to 5 or 3 seconds fix this?

**Comment by Makkkkus** [comment]
Server is deprecated. Closing.
