### ISSUE TITLE
Inventory item stacks become stacks of single items on servers

### ISSUE THREAD

**Issue by Tr0d0n** [chrisj42/minicraft-plus-revived#77]
Occasionally, the inventory of the player suddenly contains only 1 item of every item he had before. The damage is mostly recoverable due to issue #74, but it can still be very annoying. This happens mainly after the player reconnects to the game, but one observation suggests it might happen when the player is online as well.

**Comment by Makkkkus** [comment]
Server is deprecated. Closing.
