### ISSUE TITLE
Chests with a lot of items cause problems such as player "duplication" on servers

### ISSUE THREAD

**Issue by Tr0d0n** [chrisj42/minicraft-plus-revived#79]
When a lot of items are being put in a chest, weird stuff happens:

- Items can't be placed but will be used when the player tries to place them.
- The game ticks have a small boundary of values, only values from when the items were put in the chest.
- Once the player who caused the issue reconnects, there are two players with the name of the player who caused the bug simultaneously: 
  - The first one doesn't do anything, and while he can take damage he won't die. He also loses the color of his clothes and his armor (the damage number is purple, just like regular damage, and not grey, which is the color of damaging players' armor).
  - The second one acts like the real player but is barely seen by other players, as he only blinks for brief moments before disappearing from their view.
- Getting in bed makes you stuck in it if you can sleep.
- Taking furniture with the power glove doesn't make it disappear from the ground.
- Items dropped on the ground disappear.
- Damage indicator doesn't show up when trying to hit blocks.
- Mobs don't take damage or move, they do deal damage when touched.

Currently, the only known way to fix this is to restart the server.
![image](https://user-images.githubusercontent.com/51539157/59268761-15a93e80-8c56-11e9-870f-71e4a17c8cfe.png)

**Comment by Makkkkus** [comment]
Could someone test this to see if it is still a bug?
